import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./content/**/*.{md,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        secondary: "#5e5e5e",
        "surface-container": "#efeeea",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#e4e2e2",
        "on-error": "#ffffff",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#444748",
        "on-tertiary-container": "#639100",
        "surface-container-high": "#e9e8e4",
        "inverse-primary": "#c8c6c5",
        "on-background": "#1b1c1a",
        "on-primary-fixed": "#1c1b1b",
        "primary-container": "#1c1b1b",
        "on-tertiary-fixed": "#121f00",
        "on-error-container": "#93000a",
        "surface-tint": "#5f5e5e",
        "on-primary-fixed-variant": "#474646",
        "primary-fixed-dim": "#c8c6c5",
        "on-secondary-container": "#626262",
        "on-primary-container": "#858383",
        background: "#faf9f5",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e3e2df",
        "inverse-on-surface": "#f2f1ed",
        "cobalt-alt": "#315CFF",
        "surface-container-low": "#f5f4f0",
        "on-secondary-fixed": "#1b1c1c",
        "surface-container-highest": "#e3e2df",
        tertiary: "#000000",
        primary: "#000000",
        surface: "#faf9f5",
        "tertiary-fixed-dim": "#96da08",
        "tertiary-container": "#121f00",
        "inverse-surface": "#30312e",
        "surface-bright": "#faf9f5",
        "tertiary-fixed": "#b1f735",
        "secondary-container": "#e1dfdf",
        error: "#ba1a1a",
        outline: "#747878",
        "border-frame": "#D9D9D4",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#334f00",
        "outline-variant": "#c4c7c7",
        "secondary-fixed-dim": "#c7c6c6",
        "surface-dim": "#dbdad6",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#e5e2e1",
        "on-secondary-fixed-variant": "#464747",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xl": "3rem",
        "space-xs": "0.25rem",
        "margin-lg": "5rem",
        margin: "1.5rem",
        gutter: "1.5rem",
        "space-sm": "0.5rem",
        "margin-md": "3rem",
        "gutter-lg": "2.5rem",
        "space-2xl": "5rem",
        "space-md": "1rem",
        "space-lg": "1.75rem",
      },
      fontFamily: {
        mono: ['"JetBrains Mono"', "monospace"],
        "headline-lg-mobile": ["Righteous", "sans-serif"],
        "headline-lg": ["Righteous", "sans-serif"],
        "body-md": ['"Inter"', "sans-serif"],
        "display-hero": ["Righteous", "sans-serif"],
        "label-sm": ['"JetBrains Mono"', "monospace"],
        "display-hero-mobile": ["Righteous", "sans-serif"],
        "label-md": ['"JetBrains Mono"', "monospace"],
        "headline-md-mobile": ["Righteous", "sans-serif"],
        "headline-md": ["Righteous", "sans-serif"],
        "headline-sm": ["Righteous", "sans-serif"],
        "metric-display": ['"JetBrains Mono"', "monospace"],
        "body-lg": ['"Inter"', "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "36px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "64px",
          { lineHeight: "68px", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "display-hero": [
          "96px",
          { lineHeight: "96px", letterSpacing: "-0.04em", fontWeight: "800" },
        ],
        "label-sm": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "500" },
        ],
        "display-hero-mobile": [
          "48px",
          { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "800" },
        ],
        "label-md": [
          "13px",
          { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" },
        ],
        "headline-md-mobile": [
          "26px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-md": [
          "36px",
          { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-sm": [
          "24px",
          { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "metric-display": [
          "72px",
          { lineHeight: "72px", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        "body-lg": [
          "20px",
          { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
